export const STAFF_HANDBOOK_SECTIONS = [
  {
    id: "first-shift",
    title: "First Shift Checklist",
    summary: "The short version for new mods getting oriented before stream starts.",
    items: [
      "Keep one or more moderators visibly present whenever stream is live.",
      "Welcome active chatters and say goodbye when people leave if the moment allows.",
      "Use warm judgment first. Be playful with regulars only when that relationship is already clear.",
      "Keep moderation decisions and user concerns in the Discord mod spaces, not public chat.",
      "When in doubt, ask Veri, Nym, or the lead mod on duty.",
    ],
  },
  {
    id: "raids-shoutouts",
    title: "Raids + Shoutouts",
    summary: "How to handle incoming raids and creator shoutouts without stepping on the lore beat.",
    items: [
      "Use !newso for regulars, friends, raids, and creators Veri specifically asks to shout out.",
      "Use !so for other content creators when a normal channel link is enough.",
      "During raid lore, wait for the magic pause before encouraging !magic.",
      "Delay shoutouts during the first 30 minutes, raid intros, or when Veri is away from the desk.",
      "Use shoutouts to help Veri notice creator friends in chat, but do not turn it into self-promo hour.",
    ],
  },
  {
    id: "chat-guidance",
    title: "Guide The Chat",
    summary: "Mods are not just guards. You can redirect the room before it catches fire.",
    items: [
      "If chat starts arguing, redirect with an obvious stream-related question.",
      "If chat is moving well, back off and let the community carry it.",
      "Use fun commands to keep the room alive when chat gets too quiet.",
      "Be patient with repeat questions. New viewers will ask the same things over and over.",
      "Do not call out lurkers.",
    ],
  },
  {
    id: "behavior",
    title: "Behavior Escalation",
    summary: "Keep decisions consistent, logged, and out of public debate.",
    items: [
      "Record meaningful actions or users to watch in the Twitch Sus List thread.",
      "Ban obvious bots immediately and report them to Twitch.",
      "Warn uninvited self-promo, then timeout and note if it continues.",
      "Ban first-time misogynistic, homophobic, racist, or coordinated harassment messages.",
      "Warn politics or religion once, then timeout and bring patterns to the mod team.",
      "Never contradict Veri or another mod in public.",
    ],
  },
  {
    id: "veri-reminders",
    title: "Veri Reminders",
    summary: "Track the practical things that are easiest to lose mid-stream.",
    items: [
      "Help track medicine every six to eight hours and confirm when it was taken.",
      "Use !medcheck when it is time for a medication reminder.",
      "Log med timing in the current stream thread so the next mod has context.",
      "Remind Veri about unfulfilled redeems during lulls between matches or segments.",
      "Refund redeems that sit for more than about half an hour without fulfillment.",
      "Post later reminders in the Remind Veri Discord channel or use !remind text.",
    ],
  },
  {
    id: "bot-management",
    title: "Bot Management",
    summary: "Most bot work stays light, but the command reference should stay current.",
    items: [
      "Most custom commands live in MixItUp on Veri's local machine.",
      "Use StreamElements shared access when you need Cloudbot modules or chat alerts.",
      "Turn off follow alerts during follow bot waves.",
      "The !collab command is one of the most likely commands to need live updates.",
      "Future MixItUp imports should update command rows by source plus external id.",
    ],
  },
  {
    id: "stream-rules",
    title: "Stream Rules Snapshot",
    summary: "Public-facing rules distilled for staff reference.",
    items: [
      "Mature channel. Under-16 viewers should leave.",
      "No prying for personal information and no sharing private information.",
      "No hate speech, hard trolling, harassment, or flaming.",
      "No controversial topics such as politics, religion, self-harm, or triggering arguments.",
      "No lowkey self-promo unless Veri or a mod invites it.",
      "Do not tag Veri for attention unless there is a real need.",
      "Use discretion. Mods can act outside the letter of a rule when safety requires it.",
    ],
  },
];

export const DEFAULT_COMMAND_REFERENCE = [
  {
    command: "!unmod",
    action: "Let Veri know an on-duty mod is stepping away or leaving.",
    type: "Channel",
    user_requirement: "Mods",
    cooldown: "",
    bot_used: "MixItUp",
    alternate: "",
    source: "manual",
    enabled: true,
  },
  {
    command: "!remod",
    action: "Let Veri know a mod is coming back on duty.",
    type: "Channel",
    user_requirement: "Mods",
    cooldown: "",
    bot_used: "MixItUp",
    alternate: "",
    source: "manual",
    enabled: true,
  },
  {
    command: "!newso",
    action: "Creator shoutout with clip or richer summary.",
    type: "Channel",
    user_requirement: "Mods",
    cooldown: "",
    bot_used: "System",
    alternate: "!so",
    source: "manual",
    enabled: true,
  },
  {
    command: "!magic",
    action: "Raid intro flavor command for the lore pause.",
    type: "Amusing",
    user_requirement: "All",
    cooldown: "",
    bot_used: "System",
    alternate: "!gif magic",
    source: "manual",
    enabled: true,
  },
  {
    command: "!medcheck",
    action: "Wellness or medicine reminder for Veri.",
    type: "Channel",
    user_requirement: "All",
    cooldown: "10 sec user",
    bot_used: "System",
    alternate: "",
    source: "manual",
    enabled: true,
  },
  {
    command: "/requests",
    action: "Open the channel point request queue.",
    type: "Twitch",
    user_requirement: "Mods",
    cooldown: "",
    bot_used: "Twitch",
    alternate: "",
    source: "manual",
    enabled: true,
  },
  {
    command: "/marker",
    action: "Add a stream marker to the VOD at the current timestamp.",
    type: "Twitch",
    user_requirement: "Mods",
    cooldown: "",
    bot_used: "Twitch",
    alternate: "",
    source: "manual",
    enabled: true,
  },
  {
    command: "!collab",
    action: "Share current or most recent collab partner information.",
    type: "Channel",
    user_requirement: "All",
    cooldown: "",
    bot_used: "SLOBS",
    alternate: "",
    source: "manual",
    enabled: true,
  },
  {
    command: "!rules",
    action: "Link viewers to stream guidelines.",
    type: "Channel",
    user_requirement: "All",
    cooldown: "",
    bot_used: "System",
    alternate: "",
    source: "manual",
    enabled: true,
  },
  {
    command: "!permit",
    action: "Give a viewer temporary permission to post a link.",
    type: "Moderation",
    user_requirement: "Mods",
    cooldown: "",
    bot_used: "StreamElements",
    alternate: "",
    source: "manual",
    enabled: true,
  },
];
