export const GAME_ACTIONS = {
  moveLeft: "move-left",
  moveUp: "move-up",
  moveRight: "move-right",
  moveDown: "move-down",
  interact: "interact",
  primary: "primary",
  secondary: "secondary",
  cast: "cast",
  reel: "reel",
  confirm: "confirm",
  cancel: "cancel",
  qteLeft: "qte-left",
  qteUp: "qte-up",
  qteRight: "qte-right",
  qteDown: "qte-down",
  pause: "pause",
  choiceOne: "choice-one",
  choiceTwo: "choice-two",
};
